### ISSUE TITLE
Satikto kontaktu skaits kas atbilst Exposures Configuration

### ISSUE THREAD

**Issue by cherijs** [ApturiCOVID/apturicovid-ios#6]
Gribētos redzēt ar cik kontaktiem dienā, vai pēdējās 14 dienas, esmu bijis exposure zonā. Respektīvi to keys skaits kas ir piestorots manā ierīcē. 

Bez "entitled authority" netieku pie api, līdzarto nesanāk saprast vai var tikt pie šādiem datiem.

"Temporary Exposure Keys" laikam tomēr tir paša keys ko pēctam salīdzina ar Exposures

**Comment by ULazdins** [comment]
Sveiks!

Īsumā: šo informāciju nav iespējams iegūt. 

Izvērstāk: pareizi novēroji, ka Temporary Exposure Keys ir paša atslēgas, vairāk par pašu Framework API var palasīt https://developer.apple.com/documentation/exposurenotification un vairāk par Framework iekšējo uzbūvi - https://www.apple.com/covid19/contacttracing

Psst - vienmēr var implementēt savu tracing algoritmu atbilstoši specifikācijai un varēsi uzzināt pilnīgi visu :)

**Comment by cherijs** [comment]
> Psst - vienmēr var implementēt savu tracing algoritmu atbilstoši specifikācijai un varēsi uzzināt pilnīgi visu :)

Laikam tas galīgi nebūs ROI :D cerēju uz super easy kautkādu getDiagnosisKeys().count
